### ISSUE TITLE
Can't start the server

### ISSUE THREAD

**Issue by gerbsen** [leejoneshane/docker-youphptube#4]
Hey, I just tried your compose script. Unfortunately, it seems to me that the mysql server is not up in time 

```
utube         | mysqlshow: Host '172.21.0.3' is not allowed to connect to this MySQL server
utube         | ERROR 1130 (HY000): Host '172.21.0.3' is not allowed to connect to this MySQL server
utube exited with code 1
mysql         | [Entrypoint] MySQL Docker Image 5.7.21-1.1.3
mysql         | [Entrypoint] Initializing database
mysql         | [Entrypoint] Database initialized
mysql         | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql         | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
mysql         | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
mysql         | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql         | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql         |
mysql         | [Entrypoint] ignoring /docker-entrypoint-initdb.d/*
mysql         |
mysql         | [Entrypoint] Server shut down
mysql         |
mysql         | [Entrypoint] MySQL init process done. Ready for start up.
mysql         |
mysql         | [Entrypoint] Starting MySQL 5.7.21-1.1.3
mysql         | [Entrypoint] MySQL Docker Image 5.7.21-1.1.3
mysql         | [Entrypoint] Starting MySQL 5.7.21-1.1.3
mysql         | [Entrypoint] MySQL Docker Image 5.7.21-1.1.3
mysql         | [Entrypoint] Starting MySQL 5.7.21-1.1.3
```

You have any ideas?

**Comment by leejoneshane** [comment]
This is a bug with the timezone files for Riyadh* on Debian: 

http://bugs.mysql.com/bug.php?id=20545 <http://bugs.mysql.com/bug.php?id=20545>
The recommended workaround is to simply ignore the warning (if you don't need those timezone of course):

mysql_tzinfo_to_sql /usr/share/lib/zoneinfo | mysql -uroot --force mysql
After importing TZ data with the --force option, you will be able to use CONVERT_TZ. Here is a transcription of what I've just done:

sh$ mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -uroot -p mysql --force 2> /dev/null
Enter password: ********
sh$ mysql -p
Enter password: ********
Server version: 5.1.49-3 (Debian)

mysql> select convert_tz(now(), 'UTC', 'CET');
+---------------------------------+
| convert_tz(now(), 'UTC', 'CET') |
+---------------------------------+
| 2013-08-13 21:04:34             |
+---------------------------------+
1 row in set (0.00 sec)

> gerbsen <notifications@github.com> 於 2018年3月18日 上午2:24 寫道：
> 
> /usr/share/zoneinfo/iso3166.tab

**Comment by gerbsen** [comment]
hey, thanks for you quick reply. but I don't really see what the time zone settings (which I don't care about) have to do with it. the `utube` is exiting before the mysql stuff with `code 1`.

**Comment by moriyas1984** [comment]
I also found it. `utube` exits with `code 1`.

**Comment by Darkknight33** [comment]
@leejoneshane 's reply is just copypasta from Stackoverflow about the warning message, without even the context on how it applies here. Look elsewhere for your solution.

https://stackoverflow.com/questions/18216198/unable-to-load-timezones

**Comment by fheuer** [comment]
Working on the same issue. Problem is the access restriction from MySQL and the docker-compose file.

When the mysql container is up you need to connect to it with
`docker exec -it mysql /bin/sh`

Login mysql:
`mysql -u root -p`
standard password is your_db_password

Here you check the permissions with
`SELECT host, user FROM mysql.user;`


I added this line to get them talk to each other:
WARNING: do not use it in production!
`grant all privileges on *.* to 'root'@'%' identified by 'your_db_password' with grant option;`
`flush privileges;`

Recheck with `mysql> SELECT host, user FROM mysql.user;`
+-----------+---------------+
| host      | user          |
+-----------+---------------+
| %         | root          |
| localhost | healthchecker |
| localhost | mysql.session |
| localhost | mysql.sys     |
| localhost | root          |
+-----------+---------------+

Restarting the container utube should now work and return something like a list of tables and "database exists!"

To use this in production you might want to rewrite Dockerfile and docker-compose.yml.

source: https://github.com/docker-library/mysql/issues/275

**Comment by FitzChevalerie-22** [comment]
Hello,

I had the same problem. I modified the docker-compose as well:

```
  mysql:
    image: mysql/mysql-server
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3336:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my_db:/var/lib/mysql
```

Now, I've this error message:

`**ERROR 2059 (HY000): Plugin caching_sha2_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/caching_sha2_password.so: No such file or directory**`

Do you have a idea
